matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "20"

before_install:
  - npm install -g pnpm

install:
  - pnpm install

script:
  pnpm electron-package-mac